/// This AST implements a subset of the PHP AST as defined
/// by https://phplang.org/spec/19-grammar.html#syntactic-grammar
/// 
/// This subset only includes nodes that can be generated by
/// THP

pub mod transformers;

/// Represents `statement-list` on the grammar,
/// and thus a whole PHP source file
pub struct PhpAst<'a> {
    pub statements: Vec<PhpStatement<'a>>,
}

/// https://phplang.org/spec/19-grammar.html#grammar-statement
/// 
/// Not fully implemented
/// 
/// statement:
///   echo-statement
pub enum PhpStatement<'a> {
    PhpEchoStatement(PhpExpressionList<'a>),
}

pub struct PhpExpressionList<'a> {
    pub expressions: Vec<PhpExpression<'a>>,
}

pub enum PhpExpression<'a> {
    PrimaryExpression(PhpPrimaryExpression<'a>),
}

/// https://phplang.org/spec/19-grammar.html#grammar-primary-expression
/// 
/// primary-expression:
///     literal
pub enum PhpPrimaryExpression<'a> {
    IntegerLiteral(&'a String),
    FloatingLiteral(&'a String),
    StringLiteral(&'a String),
}

